git clone git://git.xfce.org/xfce/exo
git clone git://git.xfce.org/xfce/garcon
git clone git://git.xfce.org/xfce/gtk-xfce-engine
git clone git://git.xfce.org/archive/libxfce4mcs
git clone git://git.xfce.org/archive/xfce-mcs-plugins
git clone git://git.xfce.org/xfce/libxfce4menu
git clone git://git.xfce.org/xfce/libxfce4ui
git clone git://git.xfce.org/xfce/libxfce4util
git clone git://git.xfce.org/xfce/libxfcegui4
git clone git://github.com/stephenc/tango-icon-naming.git
git clone git://git.xfce.org/xfce/thunar
git clone git://git.xfce.org/xfce/tumbler
git clone git://git.xfce.org/archive/xfce-mcs-manager
git clone git://git.xfce.org/xfce/xfce-utils
git clone git://git.xfce.org/xfce/xfce4-appfinder
git clone git://git.xfce.org/art/xfce4-artwork
git clone git://git.xfce.org/xfce/xfce4-datetime-plugin
git clone git://git.xfce.org/xfce/xfce4-dev-tools
git clone git://git.xfce.org/xfce/xfce4-docs
git clone git://git.xfce.org/art/xfce4-icon-theme
git clone git://git.xfce.org/apps/xfce4-mixer
git clone git://git.xfce.org/panel-plugins/xfce4-netload-plugin
git clone git://git.xfce.org/panel-plugins/xfce4-notes-plugin
git clone git://git.xfce.org/apps/xfce4-notifyd
git clone git://git.xfce.org/xfce/xfce4-panel
git clone git://git.xfce.org/xfce/xfce4-docs
git clone git://git.xfce.org/panel-plugins/xfce4-quicklauncher-plugin
git clone git://git.xfce.org/apps/xfce4-screenshooter
git clone git://git.xfce.org/xfce/xfce4-session
git clone git://git.xfce.org/xfce/xfce4-settings
git clone git://git.xfce.org/apps/xfce4-taskmanager
git clone git://git.xfce.org/xfce/xfce4-docs
git clone git://git.xfce.org/archive/xfce4-terminal
git clone git://git.xfce.org/archive/xfce4-themes
git clone git://git.xfce.org/bindings/xfce4-vala
git clone git://git.xfce.org/panel-plugins/xfce4-verve-plugin
git clone git://git.xfce.org/panel-plugins/xfce4-wavelan-plugin
git clone git://git.xfce.org/panel-plugins/xfce4-xkb-plugin
git clone git://git.xfce.org/xfce/xfconf
git clone git://git.xfce.org/xfce/xfdesktop
git clone git://git.xfce.org/art/xfwm4-themes
git clone git://git.xfce.org/xfce/xfwm4

