git clone git://git.xfce.org/xfce/libxfce4ui
git clone git://git.gnome.org/vte
git clone git://git.xfce.org/xfce/libxfce4util
git clone git://git.xfce.org/xfce/xfconf
git clone git://git.xfce.org/xfce/libxfce4ui
git clone git://git.xfce.org/xfce/exo
git clone git://git.xfce.org/xfce/garcon
git clone git://git.xfce.org/xfce/gtk-xfce-engine
git clone git://git.gnome.org/libwnck
git clone git://git.gnome.org/libglade
git clone git://git.xfce.org/xfce/libxfce4ui
git clone git://git.xfce.org/xfce/thunar
git clone git://git.xfce.org/xfce/thunar-volman
git clone git://git.xfce.org/xfce/tumbler
git clone git://git.xfce.org/xfce/xfce4-appfinder
git clone git://git.xfce.org/xfce/xfce4-panel
git clone git://git.xfce.org/xfce/xfce4-power-manager
git clone git://git.xfce.org/xfce/xfce4-session
git clone git://git.xfce.org/xfce/xfce4-settings
git clone git://git.xfce.org/xfce/xfdesktop
git clone git://git.xfce.org/xfce/xfwm4
git clone git://git.xfce.org/apps/terminal

