wget -c http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.xz
wget -c http://ftp.gnu.org/gnu/automake/automake-1.12.2.tar.xz
wget -c http://ftp.gnu.org/gnu/bash/bash-4.2.tar.gz
wget -c http://ftp.gnu.org/gnu/binutils/binutils-2.22.tar.bz2
wget -c http://ftp.gnu.org/gnu/bison/bison-2.6.2.tar.xz
wget -c http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
wget -c http://sourceforge.net/projects/check/files/check/0.9.8/check-0.9.8.tar.gz
wget -c http://ftp.gnu.org/gnu/coreutils/coreutils-8.17.tar.xz
wget -c http://ftp.gnu.org/gnu/dejagnu/dejagnu-1.5.tar.gz
wget -c http://ftp.gnu.org/gnu/diffutils/diffutils-3.2.tar.gz
wget -c http://prdownloads.sourceforge.net/e2fsprogs/e2fsprogs-1.42.5.tar.gz
wget -c http://prdownloads.sourceforge.net/expect/expect5.45.tar.gz
wget -c ftp://ftp.astron.com/pub/file/file-5.11.tar.gz
wget -c http://ftp.gnu.org/gnu/findutils/findutils-4.4.2.tar.gz
wget -c http://prdownloads.sourceforge.net/flex/flex-2.5.35.tar.bz2
wget -c http://ftp.gnu.org/gnu/gawk/gawk-4.0.1.tar.xz
wget -c http://ftp.gnu.org/gnu/gcc/gcc-4.7.1/gcc-4.7.1.tar.bz2
wget -c http://ftp.gnu.org/gnu/gdbm/gdbm-1.10.tar.gz
wget -c http://ftp.gnu.org/gnu/gettext/gettext-0.18.1.1.tar.gz
wget -c http://ftp.gnu.org/gnu/glibc/glibc-2.16.0.tar.xz
wget -c http://ftp.gnu.org/gnu/gmp/gmp-5.0.5.tar.xz
wget -c http://ftp.gnu.org/gnu/grep/grep-2.13.tar.xz
wget -c http://ftp.gnu.org/gnu/groff/groff-1.21.tar.gz
wget -c http://ftp.gnu.org/gnu/grub/grub-2.00.tar.xz
wget -c http://ftp.gnu.org/gnu/gzip/gzip-1.5.tar.xz
wget -c http://anduin.linuxfromscratch.org/sources/LFS/lfs-packages/conglomeration//iana-etc/iana-etc-2.30.tar.bz2
wget -c http://ftp.gnu.org/gnu/inetutils/inetutils-1.9.1.tar.gz
wget -c http://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-3.5.0.tar.xz
wget -c http://ftp.altlinux.org/pub/people/legion/kbd/kbd-1.15.3.tar.gz
wget -c http://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-9.tar.xz
wget -c http://www.greenwoodsoftware.com/less/less-444.tar.gz
wget -c http://www.linuxfromscratch.org/lfs/downloads/development/lfs-bootscripts-20120725.tar.bz2
wget -c http://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.2.1.tar.gz
wget -c http://ftp.gnu.org/gnu/libtool/libtool-2.4.2.tar.gz
wget -c http://www.kernel.org/pub/linux/kernel/v3.x/linux-3.5.tar.xz
wget -c http://ftp.gnu.org/gnu/m4/m4-1.4.16.tar.bz2
wget -c http://ftp.gnu.org/gnu/make/make-3.82.tar.bz2
wget -c http://download.savannah.gnu.org/releases/man-db/man-db-2.6.2.tar.xz
wget -c http://www.kernel.org/pub/linux/docs/man-pages/man-pages-3.41.tar.xz
wget -c http://www.multiprecision.org/mpc/download/mpc-1.0.tar.gz
wget -c http://www.mpfr.org/mpfr-3.1.1/mpfr-3.1.1.tar.xz
wget -c ftp://ftp.gnu.org/gnu/ncurses/ncurses-5.9.tar.gz
wget -c http://ftp.gnu.org/gnu/patch/patch-2.6.1.tar.bz2
wget -c http://www.cpan.org/src/5.0/perl-5.16.0.tar.bz2
wget -c http://pkgconfig.freedesktop.org/releases/pkg-config-0.27.tar.gz
wget -c http://procps.sourceforge.net/procps-3.2.8.tar.gz
wget -c http://prdownloads.sourceforge.net/psmisc/psmisc-22.19.tar.gz
wget -c http://ftp.gnu.org/gnu/readline/readline-6.2.tar.gz
wget -c http://ftp.gnu.org/gnu/sed/sed-4.2.1.tar.bz2
wget -c http://pkg-shadow.alioth.debian.org/releases/shadow-4.1.5.1.tar.bz2
wget -c http://www.infodrom.org/projects/sysklogd/download/sysklogd-1.5.tar.gz
wget -c http://download.savannah.gnu.org/releases/sysvinit/sysvinit-2.88dsf.tar.bz2
wget -c http://ftp.gnu.org/gnu/tar/tar-1.26.tar.bz2
wget -c http://prdownloads.sourceforge.net/tcl/tcl8.5.12-src.tar.gz
wget -c http://www.iana.org//time-zones/repository/releases/tzdata2012e.tar.gz
wget -c http://ftp.gnu.org/gnu/texinfo/texinfo-4.13a.tar.gz
wget -c http://www.freedesktop.org/software/systemd/systemd-188.tar.xz
wget -c http://anduin.linuxfromscratch.org/sources/other/udev-lfs-188.tar.bz2
wget -c http://www.kernel.org/pub/linux/utils/util-linux/v2.21/util-linux-2.21.2.tar.xz
wget -c ftp://ftp.vim.org/pub/vim/unix/vim-7.3.tar.bz2
wget -c http://tukaani.org/xz/xz-5.0.4.tar.xz
wget -c http://www.zlib.net/zlib-1.2.7.tar.bz2
