wget -c http://www.linuxfromscratch.org/patches/lfs/development/bash-4.2-fixes-8.patch
wget -c http://www.linuxfromscratch.org/patches/lfs/development/binutils-2.22-build_fix-1.patch
wget -c http://www.linuxfromscratch.org/patches/lfs/development/bzip2-1.0.6-install_docs-1.patch
wget -c http://www.linuxfromscratch.org/patches/lfs/development/coreutils-8.17-i18n-1.patch
wget -c http://www.linuxfromscratch.org/patches/lfs/development/flex-2.5.35-gcc44-1.patch
wget -c http://www.linuxfromscratch.org/patches/lfs/development/kbd-1.15.3-upstream_fixes-1.patch
wget -c http://www.linuxfromscratch.org/patches/lfs/development/kbd-1.15.3-backspace-1.patch
wget -c http://www.linuxfromscratch.org/patches/lfs/development/kmod-9-testsuite-1.patch
wget -c http://www.linuxfromscratch.org/patches/lfs/development/patch-2.6.1-test_fix-1.patch
wget -c http://www.linuxfromscratch.org/patches/lfs/development/perl-5.16.0-libc-2.patch
wget -c http://www.linuxfromscratch.org/patches/lfs/development/procps-3.2.8-fix_HZ_errors-1.patch
wget -c http://www.linuxfromscratch.org/patches/lfs/development/procps-3.2.8-watch_unicode-1.patch
wget -c http://www.linuxfromscratch.org/patches/lfs/development/readline-6.2-fixes-1.patch
